---
efiBootLoader: "systemd-boot"
kernelSearchPath: "/boot"
kernelPattern: "^vmlinuz-linux$"
loaderEntries:
  - "timeout 3"
  - "console-mode max"
kernelParams: [ "quiet" ]
installEFIFallback: true
installHybridGRUB: false
efiBootloaderId: "DeveloperOS"
