---
efi:
  mountPoint: "/boot"
  recommendedSize: 550MiB
  minimumSize: 300MiB
  label: "ESP"

userSwapChoices:
  - none
  - small
  - suspend
  - file

luksGeneration: luks2
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultPartitionTableType: gpt
requiredPartitionTableType: gpt
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]
essentialMounts: [ "live-*", "control", "ventoy" ]
enableLuksAutomatedPartitioning: false
preCheckEncryption: false
lvm:
  enable: true

partitionLayout:
  - name: "developer_os"
    filesystem: "ext4"
    mountPoint: "/"
    size: 100%
    minSize: 15G
