---
dontChroot: true
timeout: 3600
verbose: true

script:
  - command: "/usr/local/share/developer-os/apply-installed-profile.sh '${ROOT}' '${USER}' 'extras'"
    timeout: 3600
    verbose: true

i18n:
  name: "Apply Developer OS profile"
