---
dontChroot: true
timeout: 300
verbose: true

script:
  - command: "/usr/local/share/developer-os/prepare-installed-mkinitcpio.sh '${ROOT}'"
    timeout: 300
    verbose: true

i18n:
  name: "Prepare mkinitcpio for installed system"
